# Generated by Django 4.2.20 on 2025-04-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_guest_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='document_type',
            field=models.CharField(choices=[('ID', 'Identity Card'), ('PP', 'Passport'), ('DL', 'Driving License')], max_length=2),
        ),
        migrations.AlterField(
            model_name='guest',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
