# Generated by Django 4.2.20 on 2025-04-16 11:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_guest_document_type_alter_guest_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
