# Generated by Django 4.2.20 on 2025-04-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
