# Generated by Django 4.2.20 on 2025-04-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_reservation_terms_agreed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Policies',
            new_name='Policy',
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Policy', 'verbose_name_plural': 'Policies'},
        ),
    ]
